export const programsDescription = [
  {
    id: 1,
    img: require('../images/videoTour.mp4'),
    title: 'Miami Tour 2023',
    description:
      'The tennis and physical training sessions will be adapted to the level of the young players',
    ageTitle: 'FOR AGES 10 AND OVER',
    subDescription:
      '7 days of intensive training for players who want to experience something new.',
    trainingTitle: 'ACTIVITIES:',
    tennisTime: 'Daily tennis training',
    tournament: 'STA Open tournament',
    amateourTennis: 'Live international amateur tennis',
    shareExperiences:
      'Share new experiences in a week that combines sports and friendship.',
  },
  {
    id: 2,
    img: require('../images/IntensiveProgramPhoto.jpg'),
    title: 'INTENSIVE CAMPS',
    description:
      'The tennis and physical training sessions will be adapted to the level of the young players',
    ageTitle: 'FOR AGES 10 AND OVER',
    subDescription: `Our 6-day intensive camp provides personalized tennis and physical training for young players of all levels. Our experienced coaches tailor sessions to each player's skill level, covering technical, tactical, and strategic aspects of the game. Our camp offers an unforgettable experience where players can thrive both on and off the court.`,
    trainingTitle: 'DEDICATED TRAINING TIME',
    tennisTime: 'Tennis: 3hs/day',
    tennisMorning: 'Morning: 1.5hs',
    tennisAfternoon: 'Afternoon: 1.5hs',
    physicalTime: 'Physical fitness: 2hs/day',
    physicalMorning: 'Morning: 1hr',
    physicalAfternoon: 'Afternoon: 1hr',
  },
  {
    id: 3,
    img: require('../images/HalfDayProgramPhoto1.jpg'),
    title: 'HALF-DAY CAMPS',
    description: `'The tennis and physical training sessions will be adapted to the level of the young players'`,
    ageTitle: 'FOR AGES 10 AND OVER',
    subDescription: `In our flexible 6-15 day half-day camp, our tailored training sessions are designed for young players of all levels, with a focus on optimizing their tennis skills. With the opportunity to socialize with other players, our camp offers a dynamic environment for growth. Led by experienced coaches and featuring both tennis and physical training, our program promotes skill development while fostering a sense of community.`,
    trainingTitle: 'DEDICATED TRAINING TIME',
    tennisTime: 'Tennis: 1 hr 30mins/day',
    physicalTime: 'Physical fitness: 1hr/day',
  },
  {
    id: 4,
    img: require('../images/2WeeksIntensiveProgram2.jpg'),
    title: '2 WEEKS INTESIVE CAMPS',
    description:
      'The tennis and physical training sessions will be adapted to the level of the young players',
    ageTitle: 'FOR AGES 10 AND OVER',
    subDescription: `Our two-week intensive camp is designed for competitive players! With 15 days of focused training, our program is tailored to the skill level of young players. Our expert coaches provide personalized tennis and physical training sessions, optimizing performance on and off the court. Elevate your game in a supportive environment where training is adapted to your needs.`,
    trainingTitle: 'DEDICATED TRAINING TIME',
    tennisTime: 'Tennis: 3hs/day',
    tennisMorning: 'Morning: 1.5hs',
    tennisAfternoon: 'Afternoon: 1.5hs',
    physicalTime: 'Physical fitness: 2hs/day',
    physicalMorning: 'Morning: 1hr',
    physicalAfternoon: 'Afternoon: 1hr',
  },
]
